apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vincewong-dev-tls
spec:
  secretName: vincewong-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: vincewong.dev
  dnsNames:
    - vincewong.dev
    - www.vincewong.dev